In [2]:
import sys, os
sys.path.append(os.path.abspath("src"))

In [19]:
from src.process_data import (
    data_loader,
    data_split,
    data_remove_nans,
    data_fill_nans,
    data_encoding,
    data_binary,
    data_train_models,
    data_metrics
)
from src.process_data import(__init__)
print("All imports successful!")

All imports successful!

In [20]:
#from src.process_data import data_loader

data_file = "sample_diabetes_mellitus_data.csv"
data = data_loader(data_file)
data.head()

Data loaded successfully. Shape: (10000, 53)

   Unnamed: 0  encounter_id  ...  solid_tumor_with_metastasis  diabetes_mellitus
0           0        214826  ...                            0                  1
1           1        246060  ...                            0                  1
2           2        276985  ...                            0                  0
3           3        262220  ...                            0                  0
4           4        201746  ...                            0                  0

[5 rows x 53 columns]

In [21]:
#from src.process_data import data_split

train, test = data_split(data)
print(train.shape, test.shape)

Split complete: 8000 training rows, 2000 testing rows.
(8000, 53) (2000, 53)

In [22]:
#from src.process_data import data_remove_nans

train, test = data_remove_nans(data_file)
train.head()

Data loaded successfully. Shape: (10000, 53)
Split complete: 8000 training rows, 2000 testing rows.
Removed NaN rows from train and test for columns: ['age', 'gender', 'ethnicity']

      Unnamed: 0  encounter_id  ...  solid_tumor_with_metastasis  diabetes_mellitus
9254        9254        185898  ...                            0                  1
1561        1561        179718  ...                            0                  1
1670        1670        204365  ...                            0                  0
6087        6087        167361  ...                            0                  0
6669        6669        213013  ...                            0                  0

[5 rows x 53 columns]

In [23]:
#from src.process_data import data_fill_nans

train, test = data_fill_nans(data_file)
train.head()

Data loaded successfully. Shape: (10000, 53)
Split complete: 8000 training rows, 2000 testing rows.
Removed NaN rows from train and test for columns: ['age', 'gender', 'ethnicity']
Filled NaN values in ['height', 'weight'] with column means.

      Unnamed: 0  encounter_id  ...  solid_tumor_with_metastasis  diabetes_mellitus
9254        9254        185898  ...                            0                  1
1561        1561        179718  ...                            0                  1
1670        1670        204365  ...                            0                  0
6087        6087        167361  ...                            0                  0
6669        6669        213013  ...                            0                  0

[5 rows x 53 columns]

In [24]:
#from src.process_data import data_encoding

train, test = data_encoding(data_file)
train.head()

Data loaded successfully. Shape: (10000, 53)
Split complete: 8000 training rows, 2000 testing rows.
Removed NaN rows from train and test for columns: ['age', 'gender', 'ethnicity']
Filled NaN values in ['height', 'weight'] with column means.
One-hot encoding applied to 'ethnicity' column.

      Unnamed: 0  ...  ethnicity_Other/Unknown
9254        9254  ...                    False
1561        1561  ...                    False
1670        1670  ...                    False
6087        6087  ...                    False
6669        6669  ...                    False

[5 rows x 57 columns]

In [25]:
#from src.process_data import data_binary

train, test = data_binary(data_file)
train[['gender_M', 'gender_F']].head()

Data loaded successfully. Shape: (10000, 53)
Split complete: 8000 training rows, 2000 testing rows.
Removed NaN rows from train and test for columns: ['age', 'gender', 'ethnicity']
Filled NaN values in ['height', 'weight'] with column means.
One-hot encoding applied to 'ethnicity' column.
Binary variables 'gender_M' and 'gender_F' created (1 = True, 0 = False).

      gender_M  gender_F
9254         0         1
1561         0         1
1670         1         0
6087         0         1
6669         0         1

In [26]:
#from src.process_data import data_train_models

train, test, model = data_train_models(data_file)
train[['diabetes_mellitus', 'predictions']].head()

Data loaded successfully. Shape: (10000, 53)
Split complete: 8000 training rows, 2000 testing rows.
Removed NaN rows from train and test for columns: ['age', 'gender', 'ethnicity']
Filled NaN values in ['height', 'weight'] with column means.
One-hot encoding applied to 'ethnicity' column.
Binary variables 'gender_M' and 'gender_F' created (1 = True, 0 = False).
✅ Logistic Regression model trained using 10 features: ['age', 'height', 'weight', 'aids', 'cirrhosis', 'hepatic_failure', 'immunosuppression', 'leukemia', 'lymphoma', 'solid_tumor_with_metastasis']

      diabetes_mellitus  predictions
9254                  1     0.353241
1561                  1     0.329062
1670                  0     0.155370
6087                  0     0.166528
6669                  0     0.115801

In [27]:
#from src.process_data import data_metrics

train_auc, test_auc = data_metrics(data_file)

Data loaded successfully. Shape: (10000, 53)
Split complete: 8000 training rows, 2000 testing rows.
Removed NaN rows from train and test for columns: ['age', 'gender', 'ethnicity']
Filled NaN values in ['height', 'weight'] with column means.
One-hot encoding applied to 'ethnicity' column.
Binary variables 'gender_M' and 'gender_F' created (1 = True, 0 = False).
✅ Logistic Regression model trained using 10 features: ['age', 'height', 'weight', 'aids', 'cirrhosis', 'hepatic_failure', 'immunosuppression', 'leukemia', 'lymphoma', 'solid_tumor_with_metastasis']
Train ROC-AUC: 0.6749
Test  ROC-AUC: 0.6522